sudo: false
language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: pypy
      env: TOXENV=pypy
    - python: 3.5
      env: TOXENV=pep8
    - python: 3.5
      env: TOXENV=func

install:
  - pip install tox

script:
  - tox -vv -r -e $TOXENV

branches:
  only:
    - master
    - gh-pages
